baseURL: http://example.org/
languageCode: en-us
title: Vinícius Komninakis
paginate: 2
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10
    br:
      languageName: ":pt-br:"
      languageAltTitle: Portuguese-Brazil
      weight: 2
      title: Vinícius Komninakis
      profileMode:
            enabled: true
            title: Quem eu sou?
            imageUrl: "#"
            imageTitle: my image
            imageWidth: 120
            imageHeight: 120
            subtitle: >
                - Hello, i am 22 years old, graduated in Analysis and systems development and a MBA degreed in Software Engineering.
                - Today i'm working as Web Developer, with great focus and interest in NodeJs (Javascript/Typescript) 
                  front-end applications, using ReactJs, GraphQL, NextJs, Jest and some Python (Apis and data engineering with pyspark and jupyter).
                - For future, in technology i'm studying Rust for a typed LP, more about k8s and infrastructure, Functional programming (without a specific language) and contents of Computer Science.
            buttons:
                - name: Blog
                  url: posts
                - name: Tags
                  url: tags

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Vinícius Komninakis
  description: "Blog, self description and links - Vinícius Komninakis"
  keywords: [Blog, Portfolio, Vinicius, Komninakis]
  author: Vinicius Komninakis
  images: ["eu-cover.jpeg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  homeInfoParams:
    Title: "Who am i?"
    Content: >
        Hello, i am 22 years old, graduated in Analysis and systems development and a MBA degreed in Software Engineering.
          - Today i'm working as Web Developer, with great focus and interest in NodeJs (Javascript/Typescript) 
            front-end applications, using ReactJs, GraphQL, NextJs, Jest and some Python (Apis and data engineering with pyspark and jupyter).
          - For future, in technology i'm studying Rust for a typed LP, more about k8s and infrastructure, Functional programming (without a specific language) and contents of Computer Science.

  socialIcons:
      - name: github
        url: "https://github.com/vNNI"
      - name: linkedin
        url: "https://www.linkedin.com/in/vinicius-komninakis/"
  
  taxonomies:
    category: categories
    tag: tags
    series: series
  
  markup:
    goldmark:
        renderer:
            unsafe: true

    editPost:
      URL: ""
      Text: "Suggest Changes" # edit text
      appendFilePath: true # to append file path to Edit link